### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by lucatacconi** [lucatacconi/crunz-ui#22]
Running each search, nothing is shown and the following error appears in the console:

`
vue.min.js:11 TypeError: Cannot read properties of undefined (reading '0')
    at a.customSearch (eval at compile (httpVueLoader.js:161:5), <anonymous>:78:72)
    at a.search (eval at compile (httpVueLoader.js:161:5), <anonymous>:339:18)
    at dn (vue.min.js:11:21974)
    at t.run (vue.min.js:11:28876)
    at Ye (vue.min.js:11:18719)
    at Array.<anonymous> (vue.min.js:11:23024)
    at _n (vue.min.js:11:22424)
vn @ vue.min.js:11
`

**Comment by flagellarmirror** [comment]
Fix
